# make two node services  one for the client on port 8080 and one for the insight server on port 5000

version: '3'

services:
  insight:
    build:
      context: .
      dockerfile: ./docker/insight/Dockerfile
    # image: nodejs
    # container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/home/node/app
    #   - node_modules:/home/node/app/node_modules
    # networks:
    #   - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js -->

  client:

    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    # image: nodejs
    # container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/home/node/app
    #   - node_modules:/home/node/app/node_modules
    # networks:
    #   - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js -->